language: node_js
node_js:
- node
env:
  global:
    secure: jftUOhpG0R4liYeASMIiivqoASEW0e0DEFqzdKYKE33KI6mOYHkItz1i2Do83Go7Y+47Jjss4xZCKkItWonYfmb7MZIKcdLZkkI8iiuFy1J49MRfBBqP+fNCJoC8wBIIe5G5dNnfcpQzVzvn7T6caZjJlJKFr4Z36Qqy4uLM3bQVNFJQZOwaJHiK0KC4LrxUE2u1/fkRJUqgBS/dE0Zn8vTtrc2Tt4cGHnTjaUS/XiiqGANypBgBMbBPKbDmBjAYlsqQXRqqekmdsRVuXZfJ/e3ycAkXaa1Y6yHpfZ1/HqXGoY5AhV3ig1u8caZXnPEGq9LXpdpKGTtVQvykMbkRe63ON73udZuIDantL2zJGQuGAezPKC8grTp5YXjT6pVV3O5IeEMJ9mQhwoNSAQsK4JDQXWBmZIXLWCmC426nCVyshygaD+l8qyC2TEpEx5yTra1ganZD/dx4infGeJif5D+gcjBn4VYh1r+PVK/ZQdz81GNM4qgtLVfSts2pQX+VqVMCwGxTAi/6RvozTGOqv3qtWPkW1FFAxLK0As+FXANHfopRtGqNwyOON2+iEW1FcL2U6TjAr60U43XHOB2SSWns2zk4gG4CrL3sqa2Chx5uwy8vWN7nK7WWHyRM3G+J/TtiahbqFhqZsXpYZKrQgmazsPsCqqODRBzwIHqQ1yY=
